### ISSUE TITLE
Calculate hash optimisation

### ISSUE THREAD

**Issue by karim-en** [Near-One/btc-light-client-contract#13]
* merkle-tools: this crate uses `sha2` crate instead of https://docs.rs/near-sdk/latest/near_sdk/env/fn.sha256.html, let's replace it and compare the gas usage before and after.
* bitcoin crate: I'm not sure about this one, so let's do some research; maybe it is possible to get rid of it. and replace it with custom helper functions.

**Comment by raventid** [comment]
@karim-en We are not using many Bitcoin crate features, so it should be possible to reimplement the subset of it to cover our use cases. But I don't know if we need to do it, `rustc` should do unused code reduction anyway, I don't see how we can improve a lot here.

For `merkle-tools` yes, makes sense to use near_sdk for sha 👍

**Comment by karim-en** [comment]
@raventid can we also use the `near_sdk` to get the block hash?

**Comment by raventid** [comment]
> @raventid can we also use the `near_sdk` to get the block hash?

I need to check it. Might be a bit tricky to do with current dependencies.
