### ISSUE TITLE
[BTC-client]: fix audit issues

### ISSUE THREAD

**Issue by karim-en** [Near-One/btc-light-client-contract#58]

**Comment by olga24912** [comment]
- [ ] Verify target on block submission
**PR with fix**: https://github.com/Near-One/btc-light-client-contract/pull/64
**Issue**: 
    - https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/6
    - https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/7
    - https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/15

- [ ] Calculate hash from the raw tx to avoid incorrect result in `verify_transaction_inclusion`
 **PR with fix**:  https://github.com/Near-One/btc-light-client-contract/pull/63
**Issue:** https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/8

- [ ] Update mainchain initial blockhash in reorg
**PR with fix:** https://github.com/Near-One/btc-light-client-contract/pull/62
**Issue:** https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/9

- [ ] Clean Forks in GC
**PR with fix:**
    - (version 1): https://github.com/Near-One/btc-light-client-contract/pull/59
    - (version 2): https://github.com/Near-One/btc-light-client-contract/pull/65
**Issue**:
    - https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/5
    - https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/14


- [ ] check that confirmations <= gc_threshold in verify_transaction_inclusion
**PR with fix:** https://github.com/Near-One/btc-light-client-contract/pull/61
**Issue:** https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/1

- [ ] make run_mainchain_gc pausable
**PR with fix:** https://github.com/Near-One/btc-light-client-contract/pull/61
**Issue:** 
    - https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/2
    - https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/10

- [ ] fix comments
**PR with fix:** https://github.com/Near-One/btc-light-client-contract/pull/61
**Issue:** https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/3

- [ ] fix +-1 error in GC
**PR with fix:** https://github.com/Near-One/btc-light-client-contract/pull/61
**Issue:** https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/4

- [ ] fix +-1 error in relayer
**PR with fix:** https://github.com/Near-One/btc-light-client-contract/pull/61
**Issue:** https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/13

- [ ] provide confirmations to verify_transaction_inclusion function in relayer
**PR with fix:** https://github.com/Near-One/btc-light-client-contract/pull/61
**Issue:** https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/11

Invalid issue: https://github.com/AuditOneAuditReviews/Aurora-btc-audit-review/issues/12
